version: '3'
services:
  betbull-mysql:
    container_name: betbull-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d

  app:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - betbull-mysql
